[project]
name = "weather-frame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "geopy>=2.4.1",
    "requests>=2.32.4",
]
